[package]
distribution = "2201.10.0"
org = "ballerinax"
name = "spotify"
version = "@toml.version@"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["Type/Connector", "Vendor/Spotify", "Area/Productivity & Collaboration"]
icon = "icon.png"
repository = "https://github.com/ballerina-platform/module-ballerinax-spotify"

[build-options]
observabilityIncluded = true

[platform.java17]
graalvmCompatible = true
